apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-newapplication
  namespace: {{ .Values.env }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: ss-newapplication
    kind: SecretStore
  target:
    name: newapplicationsecrets
    creationPolicy: Owner
  data:
  - secretKey: es-newapplicationsecretpassword
    remoteRef:
      key: secret/newapplicationsecretpassword
  - secretKey: es-newapplicationsecretuser
    remoteRef:
      key: secret/newapplicationsecretuser
