apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ss-newapplication
  namespace: {{ .Values.env }}
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      identityId: {{ .Values.managed_identity_created_by_aks_client_id }}
      vaultUrl: {{ .Values.kv_uri }}

