apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-db-js-wordpress-pv-${ENVIRONMENT}
  labels:
    name: wp-db-js-wordpress-pv-${ENVIRONMENT}
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/compose_data/wordpress-${ENVIRONMENT}-data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-db-js-wordpress-pvc
  namespace: k8s-${ENVIRONMENT}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: wp-db-js-wordpress-pv-${ENVIRONMENT}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-db-js-wordpress-deployment
  namespace: k8s-${ENVIRONMENT}
  labels:
    app: wordpress-application
spec:
  selector:
    matchLabels:
      project: wp-db-js-wordpress-${ENVIRONMENT}
  replicas: ${COUNT_REPLICAS}
  template:
    metadata:
      labels:
        project: wp-db-js-wordpress-${ENVIRONMENT}
    spec:
      containers:
        - name: wp-db-js-wordpress-${ENVIRONMENT}
          image: ghcr.io/isostheneia94/wordpress:${WP_IMAGE}
          env:
          - name : WORDPRESS_DB_HOST
            value: wp-db-js-mysql-service.k8s-${ENVIRONMENT}.svc.cluster.local  #db
          - name : WORDPRESS_DB_USER
            value: ${DB_USER}
          - name : WORDPRESS_DB_PASSWORD
            value: ${DB_PASSWORD}
          - name : WORDPRESS_DB_NAME
            value: ${DB_NAME}
          volumeMounts:
          - mountPath: /var/www/html
            name     :  wp-db-js-wordpress-pv-storage
      volumes:
      - name : wp-db-js-wordpress-pv-storage
        persistentVolumeClaim:
          claimName: wp-db-js-wordpress-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: wp-db-js-wordpress-service
  namespace: k8s-${ENVIRONMENT}
  labels:
    env: ${ENVIRONMENT}
    owner: MaxVerbitskiy
spec:
  selector:
    project: wp-db-js-wordpress-${ENVIRONMENT}
  ports:
    - name      : wp-listener
      protocol  : TCP
      port      : 80
      targetPort: 8000
      nodePort  : ${WORDPRESS_K8S_PORT}
  type: NodePort