name: Kubernetes pods CD dev
on:
  workflow_dispatch:
    inputs:
      js_image_dev:
        required: true
        type: string
        default: '2023.03.20.14.56.45-1'
      wp_image_dev:
        required: true
        type: string
        default: '2023.03.21.13.20.35-1'
      namespace_extended_number:
        required: true
        type: string
        default: '010000'
      #runner_container_ip:
        #required: true
        #type: string
        #default: '172.17.0.0'

jobs:
  environment_deploy:
    runs-on:
      - self-hosted
    environment: dev

    steps:
    - uses: actions/checkout@v3
    #- name: Set variable
      #run: echo "NUMBER=$(date +"%d%H%M")" >> $GITHUB_ENV

    - name: Build kubernetes deployment / init
      working-directory: ./terraform/kubernetes
      run: terraform init

    - name: Build kubernetes deployment / plan
      working-directory: ./terraform/kubernetes
      env:
        TF_VAR_replicas: 2
        TF_VAR_environment: 'dev'
        TF_VAR_github_host: 'softteco' #'isostheneia94'
        DB_USER: ${{ secrets.WORDPRESS_DB_USER }}
        DB_PASSWORD: ${{ secrets.WORDPRESS_DB_PASSWORD }}
        DB_NAME: ${{ secrets.WORDPRESS_DB_NAME }}
        TF_VAR_wp_image: ${{ inputs.wp_image_dev }}
        TF_VAR_js_image: ${{ inputs.js_image_dev }}
        TF_VAR_db_image: '5.7'
        CLIENT_CERTIFICATE: ${{ secrets.K8S_CLIENT_CERTIFICATE }} 
        CLIENT_KEY: ${{ secrets.K8S_CLIENT_KEY }}
        CLUSTER_CA_CERTIFICATE: ${{ secrets.K8S_CLUSTER_CA_CERTIFICATE }}
        GITHUB_CONNECT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_VAR_namespace_extended_name_number: ${{ inputs.namespace_extended_number}}
        HOST: ${{ env.K8S_HOST_ADDRESS }}
        DOCKER_CONFIG_GHCR_AUTH: ${{ secrets.DOCKER_CONFIG_GHCR_AUTH }}
        TF_VAR_wp_deploy_port: 8000
        TF_VAR_wp_target_port: 8000
        TF_VAR_js_deploy_port: 3000
        TF_VAR_js_target_port: 3000
        TF_VAR_mysql_deploy_port: 3306
        TF_VAR_mysql_target_port: 3306
        #TF_VAR_runner_container_ip: ${{ inputs.runner_container_ip }}
      run: terraform plan -var "db_user=${DB_USER}" -var "db_password=${DB_PASSWORD}" -var "db_name=${DB_NAME}" -var "client_certificate=${CLIENT_CERTIFICATE}" -var "client_key=${CLIENT_KEY}" -var "cluster_ca_certificate=${CLUSTER_CA_CERTIFICATE}" -var "github_access_token=${GITHUB_CONNECT_TOKEN}" -var "host=${HOST}" -var "docker_config_ghcr_auth=${DOCKER_CONFIG_GHCR_AUTH}"

    - name: Build kubernetes deployment / apply
      working-directory: ./terraform/kubernetes
      env:
        TF_VAR_replicas: 2
        TF_VAR_environment: 'dev'
        TF_VAR_github_host: 'softteco' #'isostheneia94'
        DB_USER: ${{ secrets.WORDPRESS_DB_USER }}
        DB_PASSWORD: ${{ secrets.WORDPRESS_DB_PASSWORD }}
        DB_NAME: ${{ secrets.WORDPRESS_DB_NAME }}
        TF_VAR_wp_image: ${{ inputs.wp_image_dev }}
        TF_VAR_js_image: ${{ inputs.js_image_dev }}
        TF_VAR_db_image: '5.7'
        CLIENT_CERTIFICATE: ${{ secrets.K8S_CLIENT_CERTIFICATE }}
        CLIENT_KEY: ${{ secrets.K8S_CLIENT_KEY }}
        CLUSTER_CA_CERTIFICATE: ${{ secrets.K8S_CLUSTER_CA_CERTIFICATE}}
        GITHUB_CONNECT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_VAR_namespace_extended_name_number: ${{ inputs.namespace_extended_number}}
        HOST: ${{ secrets.K8S_HOST_ADDRESS }}
        #TF_VAR_host: ${{ secrets.K8S_HOST_ADDRESS }}
        DOCKER_CONFIG_GHCR_AUTH: ${{ secrets.DOCKER_CONFIG_GHCR_AUTH }}
        TF_VAR_wp_deploy_port: 8000
        TF_VAR_wp_target_port: 8000
        TF_VAR_js_deploy_port: 3000
        TF_VAR_js_target_port: 3000
        TF_VAR_mysql_deploy_port: 3306
        TF_VAR_mysql_target_port: 3306
        #TF_VAR_runner_container_ip: ${{ inputs.runner_container_ip }}
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u isostheneia94 --password-stdin && terraform apply -auto-approve -var "db_user=${DB_USER}" -var "db_password=${DB_PASSWORD}" -var "db_name=${DB_NAME}" -var "client_certificate=${CLIENT_CERTIFICATE}" -var "client_key=${CLIENT_KEY}" -var "cluster_ca_certificate=${CLUSTER_CA_CERTIFICATE}" -var "github_access_token=${GITHUB_CONNECT_TOKEN}" -var "host=${HOST}" -var "docker_config_ghcr_auth=${DOCKER_CONFIG_GHCR_AUTH}"

  #CD_prod_trigger:
    #runs-on: self-hosted
    #environment: dev
    #needs: [environment_deploy]
    #steps:
    #- uses: actions/checkout@v3

    #- name: run CD
      #env: 
        #NAMESPACE_EXTENDED_NUMBER: ${{ inputs.namespace_extended_number}}
      #run: gh workflow run main_cd_prod.yml -f js_image_prod=2023.02.28.14.16.01-4292369971 -f wp_image_prod=2023.02.10.14.23.00-4143421464 -f namespace_extended_number=${NAMESPACE_EXTENDED_NUMBER} f runner_container_ip=${{ inputs.runner_container_ip }}