name: Kubernetes pods CI

#on:
  #push:
    #branches: [ "main" ]
    #paths:
      #- '**/Dockerfile.**'
  #pull_request:
    #branches: [ "main" ]

on:
  workflow_dispatch:
  #pull_request:
    #branches: - 'main'
  #push:
    #branches:
      #- 'mxm_vrbtskiy_main'

jobs:
  pre_build_set_variables:
    runs-on: self-hosted

    outputs:
      output_tag: ${{ steps.tag_js_wp.outputs.tag }}
      output_number_k8s_namespace: ${{ steps.namespace_number.outputs.tag }}
      output_owner_lowercase: ${{ steps.string.outputs.lowercase }}
      #output_runner_container_id: ${{ steps.runner_container_id.id }}
      #output_runner_container_ip: ${{ steps.runner_container_ip.ip }}
     
    steps:
      - id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository_owner }}


      - id: tag_js_wp
        run: echo "tag=$(date +"%Y.%m.%d.%H.%M.%S")-${{ github.run_id }}" >> $GITHUB_OUTPUT

      - id: namespace_number
        run: echo "tag=$(date +"%d%H%M")" >> $GITHUB_OUTPUT

      #- id: install_packages
        #run: sudo apt-get install software-properties-common -y && sudo apt-add-repository universe -y && sudo apt-get update && sudo apt-get install python3-pip -y && sudo pip3 install python-dateutil && sudo pip3 install requests
        #run: echo "id=$(docker ps -a | grep runner | awk '{print $1}' | head -n 1)" >> $GITHUB_OUTPUT

      #- id: runner_container_ip
        #run: echo "ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${{ needs.pre_build_set_variables.outputs.output_runner_container_id }})" >> $GITHUB_OUTPUT
  
  build_images:
    runs-on: self-hosted
    needs: pre_build_set_variables
    steps:
    - uses: actions/checkout@v3

    - name: Build the wordpress Docker image
      run: docker build --file Dockerfile.wordpress --tag ghcr.io/${{ needs.pre_build_set_variables.outputs.output_owner_lowercase }}/wordpress:${{ needs.pre_build_set_variables.outputs.output_tag }} .

    - name: Build the crash-js-app Docker image
      run: docker build --file Dockerfile.optimized.crash-js-app --tag ghcr.io/${{ needs.pre_build_set_variables.outputs.output_owner_lowercase }}/crash-js-app:${{ needs.pre_build_set_variables.outputs.output_tag }} .

  login_and_push_to_container_registry:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    needs: [pre_build_set_variables, build_images]
    steps:
    - uses: actions/checkout@v3

    #- name: Login to container registry
      #env:
        #DOCKER_TOKEN: ${{ secrets.DOCKER_CONFIG_GHCR_AUTH }}
      #run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u softteco --password-stdin #${{ needs.pre_build_set_variables.outputs.output_owner_lowercase }} --password-stdin #mvrbtsk --password-stdin

    - name: Log in to the Container registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} #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 #${{ secrets.ISOSTHENEIA94_PAT }} #${{ secrets.GITHUB_TOKEN }}

    #- name: Log in to registry
      # This is where you will update the personal access token to GITHUB_TOKEN
      #run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u softteco --password-stdin

    - name: Push to container registry js image
      run: docker push ghcr.io/${{ needs.pre_build_set_variables.outputs.output_owner_lowercase }}/crash-js-app:${{ needs.pre_build_set_variables.outputs.output_tag }}

    - name: Push to container registry wordpress image
      run: docker push ghcr.io/${{ needs.pre_build_set_variables.outputs.output_owner_lowercase }}/wordpress:${{ needs.pre_build_set_variables.outputs.output_tag }}

  delete_old_images_from_github_container_registry:
    runs-on: self-hosted
    needs: [pre_build_set_variables, build_images, login_and_push_to_container_registry]
    #working-directory: .github/actions/
    steps:
    - uses: actions/checkout@v2

    #- name: install dependencies
      #run: sudo apt-get update && sudo apt-get install python3-pip -y && sudo pip3 install python-dateutil && sudo pip3 install requests

    - name: Use script for deleting 11-th image in container registry js
      run: .github/actions/ghcr-prune-3.py --token ${{secrets.GITHUB_TOKEN}} --container crash-js-app --org softteco --number 10

    - name: Use script for deleting 11-th image in container registry wp
      run: .github/actions/ghcr-prune-3.py --token ${{secrets.GITHUB_TOKEN}} --container wordpress --org softteco --number 10

  trivy_secure:
    runs-on: self-hosted
    needs: [pre_build_set_variables, build_images, login_and_push_to_container_registry, delete_old_images_from_github_container_registry]
    steps:
    - name: Run Trivy to js-app image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/${{ needs.pre_build_set_variables.outputs.output_owner_lowercase }}/crash-js-app:${{ needs.pre_build_set_variables.outputs.output_tag }}'
        format: 'table'
        #exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Run trivy to WordPress image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/${{ needs.pre_build_set_variables.outputs.output_owner_lowercase }}/wordpress:${{ needs.pre_build_set_variables.outputs.output_tag }}'
        format: 'table'
        #exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

  #CD_trigger:
    #runs-on: self-hosted
    #needs: [pre_build_set_variables, trivy_secure]
    #steps:
    #- uses: actions/checkout@v3

    #- name: run CD
      #working-directory: .github/workflows/terraform
      #env:
        #NAMESPACE_EXTENDED_NUMBER: ${{ needs.pre_build_set_variables.outputs.output_number_k8s_namespace }}
      #run: gh workflow run CD.yml -f js_image_number=1 -f wp_image_number=3
      #run: gh workflow run main_cd_dev.yml -f js_image_dev=2023.02.28.14.16.01-4292369971 -f wp_image_dev=2023.02.10.14.23.00-4143421464 -f namespace_extended_number=${NAMESPACE_EXTENDED_NUMBER} #-f runner_container_ip=${{needs.pre_build_set_variables.outputs.output_runner_container_ip}}