env: "dev"
secrets:
  - name: ""
  - name: ""
kv_tenant_id: ""
kv_name: ""
kv_uri: ""
user_assigned_identity_id: ""
user_assigned_client_id: "" 
secrets-store-csi-driver:
 enableSecretRotation: true
#aks_public_ip: ""
aks_fqdn: ""
owner_email: ""
personal_fqdn: ""
secretObjects:
  - data:
    - key: ""
      objectName: ""
    secretName: ""
    type: ""
  - data:
    - key: ""
      objectName: ""
    secretName: ""
    type: ""
