apiVersion: v1
kind: Service
metadata:
  name: docker-vue
  namespace: {{ .Values.env }}
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: docker-vue
  type: ClusterIP
