name: azure-kubernetes-service-prod-cd

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "feature/**"
    paths:
      - terraform/aks/**

env:
  ENVIRONMENT: 'prod'

jobs:
  
  environment_deploy:
    runs-on:
      - self-hosted
    steps:
    - uses: actions/checkout@v3
      name: pre checkout

    - name: Build kubernetes deployment / init
      working-directory: ./terraform/aks
      run: terraform init

    - name: Build kubernetes deployment / plan
      working-directory: ./terraform/aks
      env:
        CLIENT_ID: ${{ secrets.MAXVRBTSK_CLIENT_ID }}
        SUBSCRIPTION_ID: ${{ secrets.MAXVRBTSK_SUBSCRIPTION_ID }}
        TENANT_ID: ${{ secrets.MAXVRBTSK_TENANT_ID }}
        CLIENT_SECRET: ${{ secrets.MAXVRBTSK_CLIENT_SECRET }}
      run: terraform plan -var "client_id=${CLIENT_ID}" -var "subscription_id=${SUBSCRIPTION_ID}" -var "tenant_id=${TENANT_ID}" -var "client_secret=${CLIENT_SECRET}"

    - name: Build kubernetes deployment / apply
      working-directory: ./terraform/aks
      env:
        CLIENT_ID: ${{ secrets.MAXVRBTSK_CLIENT_ID }}
        SUBSCRIPTION_ID: ${{ secrets.MAXVRBTSK_SUBSCRIPTION_ID }}
        TENANT_ID: ${{ secrets.MAXVRBTSK_TENANT_ID }}
        CLIENT_SECRET: ${{ secrets.MAXVRBTSK_CLIENT_SECRET }}
      run: terraform apply -auto-approve -var "client_id=${CLIENT_ID}" -var "subscription_id=${SUBSCRIPTION_ID}" -var "tenant_id=${TENANT_ID}" -var "client_secret=${CLIENT_SECRET}"
