name: Kubernetes pods CD prod
on:
  workflow_dispatch:
    inputs:
      existing-tf-workspace-prod:
        required: true
        type: string
        default: ' '
      ns-extended-number:
        required: true
        type: string
        default: '010000'
      gh-host:
        required: true
        type: string
        default: 'softteco'

permissions:
      contents: read
      id-token: write
      packages: write

env:
  ENVIRONMENT: 'prod'
  ARM_CLIENT_ID: ${{ secrets.MAXVRBTSK_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.MAXVRBTSK_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.MAXVRBTSK_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.MAXVRBTSK_SUBSCRIPTION_ID }}
  AZURE_CLIENT_ID: ${{ secrets.MAXVRBTSK_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.MAXVRBTSK_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.MAXVRBTSK_TENANT_ID }}
      
jobs:
  environment_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
    - name: pre checkout
      uses: actions/checkout@v3

    - name: az cli login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.MAXVRBTSK_CLIENT_ID }}
        tenant-id: ${{ secrets.MAXVRBTSK_TENANT_ID }}
        subscription-id: ${{ secrets.MAXVRBTSK_SUBSCRIPTION_ID }}

    - name: azure cli script
      uses: azure/CLI@v1
      with:
        azclientversion: latest
        inlineScript: |
          az account show
          az group list

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: 'ghcr.io'
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build kubernetes deployment / init
      working-directory: ./terraform/kubernetes
      run: terraform init


    - name: Build kubernetes deployment / plan (if workspace exists)
      if: ${{ github.event.inputs.existing_tf_workspace_prod}} == 'prod'
      working-directory: ./terraform/kubernetes
      env:
        TF_VAR_environment: $ENVIRONMENT
        TF_VAR_gh-host: ${{ needs.creating_tag.outputs.gh_owner_lc }}
        DB_USER: ${{ secrets.WORDPRESS_DB_USER_PROD }}
        DB_PASSWORD: ${{ secrets.WORDPRESS_DB_PASSWORD_PROD }}
        DB_NAME: ${{ secrets.WORDPRESS_DB_NAME_PROD }}
        GITHUB_CONNECT_TOKEN: ${{ secrets.MAXVRBTSK_GH_TOKEN }}
        DOCKER_CONFIG_GHCR_AUTH: ${{ secrets.DOCKER_CONFIG_GHCR_AUTH }}
        NAMESPACE_EXTENDED_NUMBER: ${{ needs.creating_tag.outputs.k8s_ns_extended_number }}
      run: |
        terraform workspace select ${ENVIRONMENT}
        terraform plan --var-file="terraform.tfvars" -var "mysql-user=${DB_USER}" -var "mysql-password=${DB_PASSWORD}" -var "mysql-name=${DB_NAME}" -var "gh-access-token=${GITHUB_CONNECT_TOKEN}" -var "docker-config-ghcr-auth=${DOCKER_CONFIG_GHCR_AUTH}" -var "ns-extended-number=${NAMESPACE_EXTENDED_NUMBER}" -out=plan-${ENVIRONMENT} -lock=false

    - name: Build kubernetes deployment / plan (if workspace doesnt exist)
      if: ${{ github.event.inputs.existing_tf_workspace_prod}} != 'prod'
      working-directory: ./terraform/kubernetes
      env:
        TF_VAR_environment: $ENVIRONMENT
        TF_VAR_gh-host: ${{ needs.creating_tag.outputs.gh_owner_lc }}
        DB_USER: ${{ secrets.WORDPRESS_DB_USER_PROD }}
        DB_PASSWORD: ${{ secrets.WORDPRESS_DB_PASSWORD_PROD }}
        DB_NAME: ${{ secrets.WORDPRESS_DB_NAME_PROD }}
        GITHUB_CONNECT_TOKEN: ${{ secrets.MAXVRBTSK_GH_TOKEN }}
        DOCKER_CONFIG_GHCR_AUTH: ${{ secrets.DOCKER_CONFIG_GHCR_AUTH }}
        NAMESPACE_EXTENDED_NUMBER: ${{ needs.creating_tag.outputs.k8s_ns_extended_number }}
      run: |
        terraform workspace new ${ENVIRONMENT}
        terraform plan --var-file="terraform.tfvars" -var "mysql-user=${DB_USER}" -var "mysql-password=${DB_PASSWORD}" -var "mysql-name=${DB_NAME}" -var "gh-access-token=${GITHUB_CONNECT_TOKEN}" -var "docker-config-ghcr-auth=${DOCKER_CONFIG_GHCR_AUTH}" -var "ns-extended-number=${NAMESPACE_EXTENDED_NUMBER}" -out=plan-${ENVIRONMENT} -lock=false

    - name: Build kubernetes deployment / apply
      working-directory: ./terraform/kubernetes
      env:
        TF_VAR_environment: $ENVIRONMENT
        TF_VAR_gh-host: ${{ needs.creating_tag.outputs.gh_owner_lc }}
        DB_USER: ${{ secrets.WORDPRESS_DB_USER_PROD }}
        DB_PASSWORD: ${{ secrets.WORDPRESS_DB_PASSWORD_PROD }}
        DB_NAME: ${{ secrets.WORDPRESS_DB_NAME_PROD }}
        GITHUB_CONNECT_TOKEN: ${{ secrets.MAXVRBTSK_GH_TOKEN }}
        DOCKER_CONFIG_GHCR_AUTH: ${{ secrets.DOCKER_CONFIG_GHCR_AUTH }}
        NAMESPACE_EXTENDED_NUMBER: ${{ needs.creating_tag.outputs.k8s_ns_extended_number }}
      run: |
        terraform workspace select ${ENVIRONMENT}
        terraform apply -auto-approve "plan-${ENVIRONMENT}"
