name: Kubernetes pods CD prod
on:
  workflow_dispatch:
    inputs:
      js_image_number_prod:
        required: true
        type: number
        default: 1
      wp_image_number_prod:
        required: true
        type: number
        default: 1

jobs:
 # here version number convert to tag_version
  set_image:
    runs-on:
      - self-hosted
    outputs:
      output_version_js: ${{ steps.js.outputs.version }}
      output_version_wp: ${{ steps.wp.outputs.version }}
    steps:
    - uses: actions/checkout@v2

    - id: js
      run: echo "version=`echo ${{ secrets.GH_TOKEN }} | ./ghcr-prune-2.py -t --container crash-js-app --number 10 --dry-run | awk '{print $5}' | head -n ${{ inputs.js_image_number_prod }} | tail -n 1 | sed 's/\[\x27//' | sed 's/\x27,//' | sed 's/\x27]//'`" >> $GITHUB_OUTPUT

    - id: wp
      run: echo "version=`echo ${{ secrets.GH_TOKEN }} | ./ghcr-prune-2.py -t --container wordpress --number 10 --dry-run | awk '{print $5}' | head -n ${{ inputs.wp_image_number_prod }} | tail -n 1 | sed 's/\[\x27//' | sed 's/\x27,//' | sed 's/\x27]//'`" >> $GITHUB_OUTPUT

  environment_deploy:
    runs-on:
      - self-hosted
    needs: [set_image]
    steps:
    - uses: actions/checkout@v2

    - name: Build kubernetes deployment
      env:
        COUNT_REPLICAS: 2
        ENVIRONMENT: 'prod'
        DB_USER: ${{ secrets.WORDPRESS_DB_USER_PROD }}
        DB_PASSWORD: ${{ secrets.WORDPRESS_DB_PASSWORD_PROD }}
        DB_NAME: ${{ secrets.WORDPRESS_DB_NAME_PROD }}
        MYSQL_K8S_PORT: 30168
        WORDPRESS_K8S_PORT: 30169
        JS_APP_K8S_PORT: 30170
        WP_IMAGE: ${{ needs.set_image.outputs.output_version_wp}}
        JS_IMAGE: ${{ needs.set_image.outputs.output_version_js}}
      run: for f in $(find kubernetes_wp_db_js/ -regex '.*\.yaml'); do envsubst < $f | kubectl apply -f -; done