name: continuous-integration

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - "main"
  push:
    branches:
      - "main"
      - "feature/**"
    paths:
      - frontend/**

jobs:
  generate_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Setup semantic-release
        shell: bash
        run: npm install -g semantic-release @semantic-release/changelog -D

      - name: Run semantic-release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  build:
    runs-on: ubuntu-latest
    needs: generate_version
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get Version
      shell: bash
      run: echo "RELEASE_VERSION=$(git tag -l --sort=version:refname | tail -n 1)" >> $GITHUB_ENV

    - name: Set owner lowercase
      shell: bash
      run: echo "OWNER_LOWERCASE=$(echo ${{ github.repository_owner }} | awk '{print tolower($0)}')" >> $GITHUB_ENV

    - name: NextJS App Docker Image Build with arguments
      shell: bash
      env:
        APP_PORT: 3002
        API_URL: http://localhost:8003/graphql
      run: docker build --build-arg APP_PORT=${APP_PORT} --build-arg API_URL=${API_URL} --tag ghcr.io/${{ env.OWNER_LOWERCASE }}/front-end:${{ env.RELEASE_VERSION }} .
      working-directory: wordpress
      
    - name: NextJS App Image Trivy Secure
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/${{ env.OWNER_LOWERCASE }}/front-end:${{ env.RELEASE_VERSION }}'
        format: 'table'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Login to ghcr.io
      shell: bash
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
    
    - name: Push to ghcr.io NextJS App image
      shell: bash
      run: docker push ghcr.io/${{ env.OWNER_LOWERCASE }}/front-end:${{ env.RELEASE_VERSION }}

    outputs:
      own_lc: ${{ env.OWNER_LOWERCASE }}
      tag: ${{ env.RELEASE_VERSION }}     

  cleanup:
    runs-on: ubuntu-latest
    needs: [generate_version, build]
    steps:
    - name: Checking out of repository
      uses: actions/checkout@v3
  
    - name: Cleanup unnecessary images and install packages
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip3 install python-dateutil 
        pip3 install requests
        ./ghcr-prune-3.py --container front-end --number 10
      working-directory: .github/bin
