name: wordpress-ci

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "feature/**"
    paths:
      - wordpress/**

jobs:
  get-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Setup Semantic Release
        shell: bash
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/exec -D

      - name: Run Semantic Release
        run: npx semantic-release --dry-run
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      release_version: ${{ env.RELEASE_VERSION }}

  build:
    runs-on: ubuntu-latest
    needs: get-version
    if: needs.get-version.outputs.release_version != ''

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set owner lowercase
        shell: bash
        run: echo "OWNER_LOWERCASE=$(echo ${{ github.repository_owner }} | awk '{print tolower($0)}')" >> $GITHUB_ENV

      - name: WP Docker Image Build
        shell: bash
        run: docker build --tag ghcr.io/${{ env.OWNER_LOWERCASE }}/wordpress:${{ needs.get-version.outputs.release_version }} .
        working-directory: wordpress

      - name: WP Image Trivy Secure
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ghcr.io/${{ env.OWNER_LOWERCASE }}/wordpress:${{ needs.get-version.outputs.release_version }}"
          format: "table"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Login to ghcr.io
        shell: bash
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Push to ghcr.io WP image
        shell: bash
        run: docker push ghcr.io/${{ env.OWNER_LOWERCASE }}/wordpress:${{ needs.get-version.outputs.release_version }}

  create-release:
    runs-on: ubuntu-latest
    needs: [build, get-version]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Setup Semantic Release
        shell: bash
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/exec -D

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Run Semantic Release
        run: npx semantic-release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cleanup:
    runs-on: ubuntu-latest
    needs: [build, get-version]
    steps:
      - name: Checking out of repository
        uses: actions/checkout@v3

      - name: Cleanup unnecessary images and install packages
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install requests
          ./ghcr-prune-5.py --container wordpress --number 10
        working-directory: .github/bin
