name: continuous-integration

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - "main"
  push:
    branches:
      - "main"
      - "feature/**"
    tags:
      - "v*"

jobs:
  generate_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Setup semantic-release
        shell: bash
        run: npm install -g semantic-release @semantic-release/changelog -D

      - name: Run semantic-release
        run: npx semantic-release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: generate_version
    steps:
    - uses: actions/checkout@v3
      name: Checking out of repository

    - name: Set tag
      run: git fetch --tags origin && echo "TAG=$(git tag -l --sort=version:refname | tail -n 1 )" >> $GITHUB_ENV

    - name: Set owner lowercase
      run: echo "OWNER_LOWERCASE=${{ github.repository_owner }}" | awk '{print tolower($0)}' >> $GITHUB_ENV

    - name: WP Docker Image Build
      working-directory: wordpress
      run: docker build --tag ghcr.io/${{ env.owner_lowercase }}/wordpress:${{ env.TAG }} .

    - name: WP Image Trivy Secure
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/${{ env.OWNER_LOWERCASE }}/wordpress:${{  env.TAG }}'
        format: 'table'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Login to ghcr.io
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
    
    - name: Push to ghcr.io WP image
      run: docker push ghcr.io/${{ env.owner_lowercase }}/wordpress:${{ env.TAG }}

    outputs:
      own_lc: ${{ env.OWNER_LOWERCASE }}
      tag: ${{ env.TAG }}     

    
  cleanup:
    runs-on: ubuntu-latest
    needs: [generate_version, build]
    steps:
    - uses: actions/checkout@v3
      name: Checking out of repository
  
    - name: Cleanup unnecessary images
      working-directory: .github/actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./ghcr-prune-3.py --container wordpress --number 10
