name: continuous-integration

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - "main"
  push:
    branches:
      - "main"
      - "feature/**"

jobs:
  build_semantic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Setup semantic-release
        shell: bash
        run: npm install -g semantic-release @semantic-release/changelog -D

      - name: Run semantic-release
        run: npx semantic-release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_with_secure:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Image Tag generate
      run: echo "tag=$(date +"%Y.%m.%d.%H.%M.%S")-${{ github.run_id }}" >> $GITHUB_ENV
    - name: Set owner lowercase
      run: echo "OWNER_LOWERCASE=$(./owner_lowercase.sh ${{ github.repository_owner }})" >> $GITHUB_ENV
    - name: WP Docker Image Build
      working-directory: wordpress
      run: docker build --tag ghcr.io/${{ env.OWNER_LOWERCASE }}/wordpress:${{ env.tag }} .

    - name: WP Image Trivy Secure
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/${{ env.OWNER_LOWERCASE }}/wordpress:${{ env.tag }}'
        format: 'table'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
    outputs:
      tag: ${{ env.tag }}
      own_lc: ${{ env.OWNER_LOWERCASE }}
  
  log_push_regitsry:
    runs-on: self-hosted
    needs:  [build_with_secure]
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to ghcr.io
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u softteco --password-stdin
    
    - name: Push to ghcr.io WP image
      run: docker push ghcr.io/${{ needs.build_with_secure.outputs.own_lc }}/wordpress:${{ needs.build_with_secure.outputs.tag }}
    
  cleanup:
    runs-on: self-hosted
    needs: [build_with_secure, log_push_regitsry]
    steps:
    - uses: actions/checkout@v3
  
    - name: Cleanup unnecessary images
      working-directory: .github/actions
      run: ./ghcr-prune-3.py --container wordpress --number 10 --token ${{ secrets.GITHUB_TOKEN }}
