name: CI for runner as container

permissions:
  packages: write

on:
  workflow_dispatch:
    inputs:
      runner_version:
        required: true
        type: string
        default: '2.303.0'
      terraform_version:
        required: true
        type: string
        default: '1.3.9'
      #image_version_after_point:
        #required: true
        #type: number
        #default: 777

jobs:
  docker_build:
    runs-on: self-hosted

    outputs:
      output_owner_lowercase: ${{ steps.string.outputs.lowercase }}

    steps:
    - id: string
      uses: ASzc/change-string-case-action@v5
      with:
        string: ${{ github.repository_owner }}

    - id: step_docker_build
      name: docker build
      working-directory: docker-github-runner-linux/
      run: docker build --file Dockerfile --build-arg RUNNER_VERSION=${{ inputs.runner_version }} --build-arg TERRAFORM_VERSION=${{ inputs.terraform_version }} --tag ghcr.io/${{ steps.string.outputs.lowercase }}/docker-github-runner-lin:5.${{ github.run_number }} .


  login_and_push_to_container_registry:
    runs-on: self-hosted
    needs: [docker_build]
    steps:
    - uses: actions/checkout@v3

    - name: Login to container registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push to container registry docker-github-runner-lin image
      run: docker push ghcr.io/${{ needs.docker_build.outputs.output_owner_lowercase }}/docker-github-runner-lin:5.${{ github.run_number }}

  delete_old_images_from_github_container_registry:
    runs-on: self-hosted
    needs: [docker_build, login_and_push_to_container_registry]
    steps:
    - uses: actions/checkout@v3

    - name: Use script for deleting 11-th image in container registry docker-github-runner-lin
      run: echo ${{ secrets.GITHUB_TOKEN }} | ./ghcr-prune-2.py -t --container docker-github-runner-lin --number 10

  trivy_secure:
    runs-on: self-hosted
    needs: [docker_build, login_and_push_to_container_registry, delete_old_images_from_github_container_registry]
    steps:
    - name: Run Trivy to docker-github-runner-lin image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/${{ needs.docker_build.outputs.output_owner_lowercase }}/docker-github-runner-lin:5.${{ github.run_number }}'
        format: 'table'
        #exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

