name: CI for runner as container

on:
  workflow_dispatch:
    inputs:
      runner_version:
        required: true
        type: string
        default: '2.303.0'
      terraform_version:
        required: true
        type: string
        default: '1.3.9'
      #image_version_after_point:
        #required: true
        #type: number
        #default: 777

jobs:
  docker_build:
    runs-on: self-hosted

    outputs:
      output_owner: ${{ steps.set_owner.owner }}
      output_owner_lowercase: ${{ steps.set_owner_lowercase.owner_lc }}
      output_runner_container_ip: ${{ steps.runner_container_ip.ip }}

    steps:
    - id: set_owner
      name: set_owner
      run: echo "owner=${{ github.repository_owner }})" >> $GITHUB_OUTPUT

    - id: set_owner_lowercase
      name: set_owner_lowercase
      run: echo "owner_lc=$(needs.docker_build.outputs.output_owner,,)" >> $GITHUB_OUTPUT

    - name: docker build
      working-directory: docker-github-runner-linux/
      #run: export owner=${{ github.repository_owner}} && export owner_lc=${owner,,} && docker build --file Dockerfile --build-arg RUNNER_VERSION=${{ inputs.runner_version }} --build-arg TERRAFORM_VERSION=${{ inputs.terraform_version }} --tag ghcr.io/${owner_lc}/docker-github-runner-lin:5.${{ github.run_number }} .
      run: docker build --file Dockerfile --build-arg RUNNER_VERSION=${{ inputs.runner_version }} --build-arg TERRAFORM_VERSION=${{ inputs.terraform_version }} --tag ghcr.io/${{ needs.docker_build.outputs.output_set_owner_lowercase }}/docker-github-runner-lin:5.${{ github.run_number }} .


  login_and_push_to_container_registry:
    runs-on: self-hosted
    needs: [docker_build]
    steps:
    - uses: actions/checkout@v3

    #- name: Login to container registry
      #run: echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u mvrbtsk --password-stdin

    - name: Push to container registry docker-github-runner-lin image
      run: docker push ghcr.io/${{ needs.docker_build.outputs.output_set_owner_lowercase }}/docker-github-runner-lin:5.${{ github.run_number }}

  delete_old_images_from_github_container_registry:
    runs-on: self-hosted
    needs: [docker_build, login_and_push_to_container_registry]
    steps:
    - uses: actions/checkout@v3

    - name: Use script for deleting 11-th image in container registry docker-github-runner-lin
      run: echo ${{ secrets.GH_TOKEN }} | ./ghcr-prune-2.py -t --container docker-github-runner-lin --number 10

  trivy_secure:
    runs-on: self-hosted
    needs: [docker_build, login_and_push_to_container_registry, delete_old_images_from_github_container_registry]
    steps:
    - name: Run Trivy to docker-github-runner-lin image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/${{ needs.docker_build.outputs.output_set_owner_lowercase }}/docker-github-runner-lin:5.${{ github.run_number }}'
        format: 'table'
        #exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

